# Generated by Django 3.2.5 on 2021-07-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollector',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
