# Generated by Django 3.2.5 on 2021-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_imagecollector_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollector',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
